module.exports = [
    
    {  
        url:'https://extranet.who.int/nutrition/gina/fr/node/add/staging-commitments',
        localeFile:'C:/Users/HP/Desktop/cpa-templates/test-methode-pdf/c01d-free-instagram-followers-generator-22-920.pdf',
        urlToWatch:'https://extranet.who.int/nutrition/gina/sites/default/files/c01d-free-instagram-followers-generator-22-920.pdf',
        name:'wb39',
        fileNewName:'C:/Users/HP/Desktop/cpa-templates/c01d-free-instagram-followers-generator-22-920.pdf'
    },
    {  
        url:'https://extranet.who.int/nutrition/gina/fr/node/add/staging-commitments',
        localeFile:'C:/Users/HP/Desktop/cpa-templates/test-methode-pdf/k0pdla-free-instagram-followers-generator-1308-pdla-5.pdf',
        urlToWatch:'https://extranet.who.int/nutrition/gina/sites/default/files/k0pdla-free-instagram-followers-generator-1308-pdla-5.pdf',
        name:'wb39',
        fileNewName:'C:/Users/HP/Desktop/cpa-templates/k0pdla-free-instagram-followers-generator-1308-pdla-5.pdf'
    },
    
    {  
        url:'https://extranet.who.int/nutrition/gina/fr/node/add/staging-commitments',
        localeFile:'C:/Users/HP/Desktop/cpa-templates/test-methode-pdf/c01d-true-free-vbucks-generator-fort-bucks-8791-villa.pdf',
        urlToWatch:'https://extranet.who.int/nutrition/gina/sites/default/files/c01d-true-free-vbucks-generator-fort-bucks-8791-villa.pdf',
        name:'wb39',
        fileNewName:'C:/Users/HP/Desktop/cpa-templates/c01d-true-free-vbucks-generator-fort-bucks-8791-villa.pdf'
    },
    {  
        url:'https://extranet.who.int/nutrition/gina/fr/node/add/staging-commitments',
        localeFile:'C:/Users/HP/Desktop/cpa-templates/test-methode-pdf/free-v-bucks-generator-c01d.pdf',
        urlToWatch:'https://extranet.who.int/nutrition/gina/sites/default/files/free-v-bucks-generator-c01d.pdf',
        name:'wb39',
        fileNewName:'C:/Users/HP/Desktop/cpa-templates/free-v-bucks-generator-c01d.pdf'
    },
    {  
        url:'https://extranet.who.int/nutrition/gina/fr/node/add/staging-commitments',
        localeFile:'C:/Users/HP/Desktop/cpa-templates/test-methode-pdf/legit-hack-fortnite-v-bucks-generator-2020-ps4-fortnite-v-bucks-hack-2020.pdf',
        urlToWatch:'https://extranet.who.int/nutrition/gina/sites/default/files/legit-hack-fortnite-v-bucks-generator-2020-ps4-fortnite-v-bucks-hack-2020.pdf',
        name:'wb39',
        fileNewName:'C:/Users/HP/Desktop/cpa-templates/legit-hack-fortnite-v-bucks-generator-2020-ps4-fortnite-v-bucks-hack-2020.pdf'
    },
    {  
        url:'https://extranet.who.int/nutrition/gina/fr/node/add/staging-commitments',
        localeFile:'C:/Users/HP/Desktop/cpa-templates/test-methode-pdf/c5md-free-vbucks-generator-fort-bucks.pdf',
        urlToWatch:'https://extranet.who.int/nutrition/gina/sites/default/files/c5md-free-vbucks-generator-fort-bucks.pdf',
        name:'wb39',
        fileNewName:'C:/Users/HP/Desktop/cpa-templates/c5md-free-vbucks-generator-fort-bucks.pdf'
    },
    {  
        url:'https://extranet.who.int/nutrition/gina/fr/node/add/staging-commitments',
        localeFile:'C:/Users/HP/Desktop/cpa-templates/test-methode-pdf/yooyoyoy-pokemon-go-hack-cheats-joystick-spoofing.pdf',
        urlToWatch:'https://extranet.who.int/nutrition/gina/sites/default/files/yooyoyoy-pokemon-go-hack-cheats-joystick-spoofing.pdf',
        name:'wb39',
        fileNewName:'C:/Users/HP/Desktop/cpa-templates/yooyoyoy-pokemon-go-hack-cheats-joystick-spoofing.pdf'
    },
    {  
        url:'https://extranet.who.int/nutrition/gina/fr/node/add/staging-commitments',
        localeFile:'C:/Users/HP/Desktop/cpa-templates/test-methode-pdf/siiv-HOW-TO-GET-NETFLIX-PREMIUM-ACCOUNT-GENERATOR-2020-ufjn7z.pdf',
        urlToWatch:'https://extranet.who.int/nutrition/gina/sites/default/files/siiv-HOW-TO-GET-NETFLIX-PREMIUM-ACCOUNT-GENERATOR-2020-ufjn7z.pdf',
        name:'wb39',
        fileNewName:'C:/Users/HP/Desktop/cpa-templates/siiv-HOW-TO-GET-NETFLIX-PREMIUM-ACCOUNT-GENERATOR-2020-ufjn7z.pdf'
    },
    {  
        url:'https://extranet.who.int/nutrition/gina/fr/node/add/staging-commitments',
        localeFile:'C:/Users/HP/Desktop/cpa-templates/test-methode-pdf/cxoc-PUBG-MOBILE-HACK-FREE-UC-GENERATOR-2020-vkfh8r.pdf',
        urlToWatch:'https://extranet.who.int/nutrition/gina/sites/default/files/cxoc-PUBG-MOBILE-HACK-FREE-UC-GENERATOR-2020-vkfh8r.pdf',
        name:'wb39',
        fileNewName:'C:/Users/HP/Desktop/cpa-templates/cxoc-PUBG-MOBILE-HACK-FREE-UC-GENERATOR-2020-vkfh8r.pdf'
    },
    {  
        url:'https://extranet.who.int/nutrition/gina/fr/node/add/staging-commitments',
        localeFile:'C:/Users/HP/Desktop/cpa-templates/test-methode-pdf/ehgw-free-clash-of-clans-gems-generator-updated-no-downloadpb808s.pdf',
        urlToWatch:'https://extranet.who.int/nutrition/gina/sites/default/files/ehgw-free-clash-of-clans-gems-generator-updated-no-downloadpb808s.pdf',
        name:'wb39',
        fileNewName:'C:/Users/HP/Desktop/cpa-templates/ehgw-free-clash-of-clans-gems-generator-updated-no-downloadpb808s.pdf'
    },
    {  
        url:'https://extranet.who.int/nutrition/gina/fr/node/add/staging-commitments',
        localeFile:'C:/Users/HP/Desktop/cpa-templates/test-methode-pdf/bwhr-floutnore-brawl-stars-hack-gems-gnsa367279-7q999tp.pdf',
        urlToWatch:'https://extranet.who.int/nutrition/gina/sites/default/files/bwhr-floutnore-brawl-stars-hack-gems-gnsa367279-7q999tp.pdf',
        name:'wb39',
        fileNewName:'C:/Users/HP/Desktop/cpa-templates/bwhr-floutnore-brawl-stars-hack-gems-gnsa367279-7q999tp.pdf'
    },
    {  
        url:'https://extranet.who.int/nutrition/gina/fr/node/add/staging-commitments',
        localeFile:'C:/Users/HP/Desktop/cpa-templates/test-methode-pdf/hackerEARTHs-34534-free-fortnite-skins-generator-yes-codes-3345.pdf',
        urlToWatch:'https://extranet.who.int/nutrition/gina/sites/default/files/hackerEARTHs-34534-free-fortnite-skins-generator-yes-codes-3345.pdf',
        name:'wb39',
        fileNewName:'C:/Users/HP/Desktop/cpa-templates/hackerEARTHs-34534-free-fortnite-skins-generator-yes-codes-3345.pdf'
    },
    {  
        url:'https://extranet.who.int/nutrition/gina/fr/node/add/staging-commitments',
        localeFile:'C:/Users/HP/Desktop/cpa-templates/test-methode-pdf/z0anl1spq2-free-fortnite-skin-generator-model-modded-skins-83632-meetha.pdf',
        urlToWatch:'https://extranet.who.int/nutrition/gina/sites/default/files/z0anl1spq2-free-fortnite-skin-generator-model-modded-skins-83632-meetha.pdf',
        name:'wb39',
        fileNewName:'C:/Users/HP/Desktop/cpa-templates/z0anl1spq2-free-fortnite-skin-generator-model-modded-skins-83632-meetha.pdf'
    },
     
    
]