module.exports = [
    {
        url:'https://calenergycorps.berkeley.edu/recommendation-letters',
        uploadeTage:'#edit-submitted-letter-of-recommendation-upload',
        btnUploadeTage:'#edit-submitted-letter-of-recommendation-upload-button',
    },
    {
        url:'https://www.imls.gov/eform/submit/2021-nomination-form',
        uploadeTage:'#edit-field-section-d-letters-und-0-upload',
        btnUploadeTage:'#edit-field-section-d-letters-und-0-upload-button',
    },
    {
        url:'https://forms.humboldt.edu/node',
        uploadeTage:'#edit-submitted-submission-information-syllabus-upload',
        btnUploadeTage:'#edit-submitted-submission-information-syllabus-upload-button',
    },
    {
        url:'https://www.ccp.edu/forms/contact-admissions',
        uploadeTage:'#edit-submitted-if-you-wish-to-attach-a-document-to-this-form-eg-transcripts-sat-scores-please-do-so-here-upload',
        btnUploadeTage:'#edit-submitted-if-you-wish-to-attach-a-document-to-this-form-eg-transcripts-sat-scores-please-do-so-here-upload-button',
    },
    {
        url:'https://info.nicic.gov/t4c/node/42',
        uploadeTage:'#edit-submitted-affirmation-letter-upload',
        btnUploadeTage:'#edit-submitted-affirmation-letter-upload-button',
    },
    {
        url:'https://www.uky.edu/president/remarks_form',
        uploadeTage:'#edit-submitted-agenda-upload-upload',
        btnUploadeTage:'#edit-submitted-agenda-upload-upload-button',
    },
    {
        url:'https://www.centralcoast.nsw.gov.au/form/seasonal-allocation-request-form',
        uploadeTage:'#edit-submitted-association-details-public-liability-insurance-upload',
        btnUploadeTage:'#edit-submitted-association-details-public-liability-insurance-upload-button',
    },
    {
        url:'https://www.shellharbour.nsw.gov.au/form/eoi-set-markets-shellharbour-lga',
        uploadeTage:'#edit-submitted-upload-market-format-structures-upload',
        btnUploadeTage:'#edit-submitted-upload-market-format-structures-upload-button',
    },
    {
        url:'https://jornades.uab.cat/orfeo/content/abstract-submission',
        uploadeTage:'#edit-submitted-short-cv-one-page-upload',
        btnUploadeTage:'#edit-submitted-short-cv-one-page-upload-button',
    },
    {
        url:'https://library.austintexas.gov/the-covid-19-files',
        uploadeTage:'#edit-field-ahc-d-files-und-0-upload--2',
        btnUploadeTage:'#edit-field-ahc-d-files-und-0-upload-button--2',
    },
    {
        url:'https://sd06.senate.ca.gov/recognition-request',
        uploadeTage:'#edit-submitted-biographical-upload',
        btnUploadeTage:'#edit-submitted-biographical-upload-button',
    },
    {
        url:'https://www.wells.edu/share-your-business-card',
        uploadeTage:'#edit-submitted-upload-business-card-upload',
        btnUploadeTage:'',
    },
    {
        url:'https://mbs.rutgers.edu/psm-campus-externshipresearch-internship-fellowship',
        uploadeTage:'#edit-submitted-please-upload-resume-here-upload',
        btnUploadeTage:'#edit-submitted-please-upload-resume-here-upload-button',
    },
    {
        url:'https://fima.ub.edu/poldoc/en/contact/proponer_documento',
        uploadeTage:'#edit-field-fitxer-0-upload',
        btnUploadeTage:'',
    },
    {
        url:'https://music.missouri.edu/webform/tell-us-your-news',
        uploadeTage:'#edit-submitted-event-image-or-pdf-upload',
        btnUploadeTage:'#edit-submitted-event-image-or-pdf-upload-button',
    },
    {
        url:'https://omed.gatech.edu/about/omed-jobs/edge-leader/apply',
        uploadeTage:'#edit-submitted-upload-current-resume-upload',
        btnUploadeTage:'#edit-submitted-upload-current-resume-upload-button',
    },
    {
        url:'https://www.naco.org/creative-counties-placemaking-challenge-application-form',
        uploadeTage:'#edit-submitted-application-pdf-upload',
        btnUploadeTage:'#edit-submitted-application-pdf-upload-button',
    },
    {
        url:'https://inrc.law.uiowa.edu/node/21569/edit',
        firstClick: '.horizontal-tab-button horizontal-tab-button-1',
        uploadeTage:'#edit-field-pdf-version-und-0-upload',
        btnUploadeTage:'#edit-field-pdf-version-und-0-upload-button',
    },
    {
        url:'https://clpp.hampshire.edu/',
        firstClick: '.fieldset-title',
        uploadeTage:'#edit-submitted-resume-its-optional-upload-your-resume-here-if-youd-like-upload',
        btnUploadeTage:'#edit-submitted-resume-its-optional-upload-your-resume-here-if-youd-like-upload-button',
    },
    {
        url:'https://www.nwcg.gov/positions/docl',
        firstClick: '[data-target="#collapseCF"]',
        uploadeTage:'#edit-submitted-feedback-form-attachment-upload',
        btnUploadeTage:'#edit-submitted-feedback-form-attachment-upload-button',
    },
    {
        url:'https://pharmacy.ucsf.edu/support',
        uploadeTage:'#edit-submitted-optional-no-attachment-upload',
        btnUploadeTage:'#edit-submitted-optional-no-attachment-upload-button',
    },
    {
        url:'https://wholeness.llu.edu/contact-us-form',
        uploadeTage:'#edit-submitted-attachment-upload',
        btnUploadeTage:'#edit-submitted-attachment-upload-button',
    },
    {
        url:'https://cbssm.med.umich.edu/training-mentoring/post-doctoral-fellowship/letter-recommendation',
        uploadeTage:'#edit-submitted-letter-of-recommendation-upload',
        btnUploadeTage:'#edit-submitted-letter-of-recommendation-upload-button',
    },
    {  
        url:'https://en.unesco.org/creativity/convention/emblem/request-endorsement-emblem',
        uploadeTage:'#edit-submitted-please-provide-in-attachment-the-completed-request-form-for-the-use-of-the-emblem-upload',
        btnUploadeTage:'#edit-submitted-please-provide-in-attachment-the-completed-request-form-for-the-use-of-the-emblem-upload-button',
    },
    {
        url:'https://www.arcadia.edu/university/offices-facilities/mail-print-services/poster-printing-request-form',
        uploadeTage:'#edit-submitted-poster-printing-upload-your-file-upload',
        btnUploadeTage:'#edit-submitted-poster-printing-upload-your-file-upload-button',
    },
    {
        url:'https://honors.njit.edu/content/dean%E2%80%99s-fund-application-undergraduate-funding',
        uploadeTage:'#edit-submitted-proposal-document-upload-upload',
        btnUploadeTage:'#edit-submitted-proposal-document-upload-upload-button',
    },
    {
        url:'https://www.cartv.gouv.qc.ca/en/request-verification-non-compliance-lartv',
        uploadeTage:'#edit-submitted-description-envoi-de-documents-upload',
        btnUploadeTage:'#edit-submitted-description-envoi-de-documents-upload-button',
    },
    {
        url:'https://nystormrecoveryopps.ny.gov/contractors/register',
        uploadeTage:'#edit-profile-contractors-field-con-attach-documents-und-0-upload',
        btnUploadeTage:'#edit-profile-contractors-field-con-attach-documents-und-0-upload-button',
    },
    {
        url:'https://international.uky.edu/About/CreativeBrief',
        uploadeTage:'#edit-submitted-submit-design-sample-idea-or-vision-upload',
        btnUploadeTage:'#edit-submitted-submit-design-sample-idea-or-vision-upload-button',
    },
    {
        url:'https://test.centralcoast.nsw.gov.au/form/feedback',
        uploadeTage:'#edit-submitted-commentss-attachment-upload',
        btnUploadeTage:'#edit-submitted-commentss-attachment-upload-button',
    },
    {
        url:'https://www.azdps.gov/contact/webmaster',
        uploadeTage:'#edit-submitted-attachments-upload',
        btnUploadeTage:'#edit-submitted-attachments-upload-button',
    },
    {
        url:'https://azdot.gov/certification-acceptance-manual-update-request',
        uploadeTage:'#edit-submitted-attachment-0-upload',
        btnUploadeTage:'#edit-submitted-attachment-0-upload-button',
    },
    {
        url:'https://effectivehealthcare.ahrq.gov/get-involved/suggest-topic',
        uploadeTage:'#edit-submitted-supporting-document-upload-document-upload',
        btnUploadeTage:'#edit-submitted-supporting-document-upload-document-upload-button',
    },
    {
        url:'https://www.icgov.org/form/request-qualification-city-hall-lobby-art-installation',
        uploadeTage:'#edit-submitted-resume-upload',
        btnUploadeTage:'#edit-submitted-resume-upload-button',
    },
    {
        url:'https://csl.uchicago.edu/form/dean-call-program-applications-university-staff',
        uploadeTage:'#edit-submitted-resume-cv-upload',
        btnUploadeTage:'#edit-submitted-resume-cv-upload-button',
    },
    {
        url:'https://wcat.novascotia.ca/contact-us',
        uploadeTage:'#edit-submitted-attachment-upload',
        btnUploadeTage:'#edit-submitted-attachment-upload-button',
    },
    {
        url:'https://www.ucalgary.ca/research/researchers/agreement-request-form',
        uploadeTage:'#edit-submitted-project-information-statement-of-work-upload',
        btnUploadeTage:'#edit-submitted-project-information-statement-of-work-upload-button',
    },
    {
        url:'https://www.ccab.org/join-our-team',
        uploadeTage:'#edit-submitted-resume-upload',
        btnUploadeTage:'#edit-submitted-resume-upload-button',
    },
    {
        url:'https://paton.bus.umich.edu/scholarships-honors/honorary-fellow-program/nomination',
        uploadeTage:'#edit-submitted-nominee-details-bio-upload',
        btnUploadeTage:'#edit-submitted-nominee-details-bio-upload-button',
    },
    {
        url:'https://campusinvolvement.umich.edu/content/exhibit-application',
        uploadeTage:'#edit-submitted-exhibit-information-images-of-artwork-upload',
        btnUploadeTage:'#edit-submitted-exhibit-information-images-of-artwork-upload-button',
    },
    {
        url:'https://www.physiology.utoronto.ca/content/summer-research-assistant-hiring-request-form',
        uploadeTage:'#edit-submitted-banking-information-upload-upload',
        btnUploadeTage:'#edit-submitted-banking-information-upload-upload-button',
    },
    {
        url:'https://www.esma.europa.eu/content/speaker-request-form',
        uploadeTage:'#edit-submitted-if-available-please-attach-an-agenda-upload',
        btnUploadeTage:'#edit-submitted-if-available-please-attach-an-agenda-upload-button',
    },
    {
        url:'https://cer.eu/job/two-research-fellow-roles',
        uploadeTage:'#edit-submitted-your-cv-upload',
        btnUploadeTage:'#edit-submitted-your-cv-upload-button',
    },
    {
        url:'https://ec.europa.eu/environment/ecoap/user/register_fr',
        uploadeTage:'#edit-profile-main-field-profile-documents-und-0-upload',
        btnUploadeTage:'#edit-profile-main-field-profile-documents-und-0-upload-button',
    },
    {
        url:'https://edge.fbk.eu/en/node/21',
        uploadeTage:'#edit-submitted-related-media-allegato-attachment-upload',
        btnUploadeTage:'#edit-submitted-related-media-allegato-attachment-upload-button',
    },
    {
        url:'https://www.cdu.edu.au/node/12113',
        uploadeTage:'#edit-submitted-business-details-insert-logo-upload',
        btnUploadeTage:'#edit-submitted-business-details-insert-logo-upload-button',
    },
    {
        url:'https://www.themorgan.org/opportunities/drawing-institute-application',
        uploadeTage:'#edit-submitted-please-upload-the-following-upload-cover-letter-upload',
        btnUploadeTage:'#edit-submitted-please-upload-the-following-upload-cover-letter-upload-button',
    },
    {
        url:'https://law.pace.edu/visiting-scholar-application',
        uploadeTage:'#edit-submitted-current-resume-or-curriculum-vitae-upload',
        btnUploadeTage:'#edit-submitted-current-resume-or-curriculum-vitae-upload-button',
    },
    {
        url:'https://circulareconomy.europa.eu/platform/fr/node/add/cecon-file-upload',
        uploadeTage:'#edit-field-cecon-upload-file-und-0-field-cecon-file-und-0-upload',
        btnUploadeTage:'#edit-field-cecon-upload-file-und-add-more',
    },
    {
        url:'https://robuenosaires.iom.int/fomulario-inscripcion',
        uploadeTage:'#edit-submitted-en-caso-de-archivo-upload',
        btnUploadeTage:'#edit-submitted-en-caso-de-archivo-upload-button',
    },
    {
        url:'https://extranet.who.int/nutrition/gina/fr/node/add/staging-commitments',
        uploadeTage:'#edit-field-file-und-0-upload',
        btnUploadeTage:'#edit-field-file-und-0-upload-button',
    },
    
    
     
]
